name: Renovate
on:
  workflow_dispatch:
  repository_dispatch:
    types: [renovate]
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on:
      labels: [ self-hosted, linux, x64 ]
      group: light

    steps:
      - uses: SwanseaUniversityMedical/workflows/.github/actions/renovate@v1.0.4-renovate
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          config: '.github/renovate.js'
        env:
          RENOVATE_HARBOR_REGISTRY: ${{ vars.HARBOR_REGISTRY }}
          RENOVATE_HARBOR_USER: ${{ vars.HARBOR_USER }}
          RENOVATE_HARBOR_TOKEN: ${{ secrets.HARBOR_TOKEN }}
